### ISSUE TITLE
이건 무슨 말인가용 ?

### ISSUE THREAD

**Issue by boseongv** [zieunv/Swift_iOS#15]
익스텐션으로 클래스 타입에 편의 이니셜라이저는 추가할 수 있지만, 지정 이니셜라이저는 추가할 수 없다.
지정 이니셜라이저와 디이니셜라이저는 반드시 클래스 타입의 구현부에 위치해야 한다.(?)

**Comment by Hoontopia** [comment]
클래스 내에는 무조건 하나 이상의 지정 이니셜라이저(Designated Initializer)를 가지고 있어야 함
편의 이니셜라이저(Convenience Initializer)는 이니셜라이저(지정 이니셜라이저 아님)인데 'convenience' 키워드가 붙은 이니셜라이저를 말하는데, 편의 이니셜라이저 내부 스코프에서 무조건 지정 이니셜라이저를 호출 해줘야 함.
ㅡ
익스텐션으로 클래스를 확장한 경우, 지정 이니셜라이저와 디이니셜라이저는 추가 할 수 없지만 'convenience' 키워드가 붙은 편의 이니셜라이저는 추가 할 수 있다는 말임 (편의 이니셜라이저 내부에서 지정 이니셜라이저를 호출해줘야겠지)
ㅡ
```swift
extension YourClass {
    // 불가
    init() {
    }

    // 불가
    deinit {
    }

    // 가능
    convenience init() {
        self.init() // 본체에 정의되어있는 지정 이니셜라이저 호출
    }
}

**Comment by boseongv** [comment]
오호 ,, 바로 이해가 되는군요 !! 감사합니닷  👍
